artifacts_root: artifacts #every thing will be saved under it 

data_ingestion: 
  root_dir: artifacts/data_ingestion  # what the directory the data will be saved 
  source_url: https://github.com/Ahmad-Amireh/end-to-end-ML-with-MLflow/raw/refs/heads/main/winequality-data.zip  # where is the data source 
  local_data_file: artifacts/data_ingestion/data.zip #where do you want to save it 
  unzip_dir: artifacts/data_ingestion

data_validation: 
  root_dir: artifacts/data_validation 
  unzip_data_dir: artifacts/data_ingestion/winequality-red.csv 
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation: 
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/winequality-red.csv 

model_trainer: 
  root_dir: artifacts/mdoel_training
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path : artifacts/data_transformation/test.csv
  model_name: model.joblib


model_evaluation: 
  root_dir: artifacts/model_evaluation
  test_data_path : artifacts/data_transformation/test.csv
  model_path: artifacts\mdoel_training\model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json